default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: EMS_development
test:
  <<: *default
  database: EMS_test
production:
  <<: *default
  database: EMS_production
  username: EMS
  password: <%= ENV['EMS_DATABASE_PASSWORD'] %>
